name: Deploy Azure Function Python

on:
  push:
    branches:
      - main  # Mude se sua branch for outra

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Zip function app files
      run: zip -r functionapp.zip .

    - name: Deploy to Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: 'intrabotsfuncrelatorio1'  # <=== coloque aqui o nome da sua Function App
        package: './functionapp.zip'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
